#!/bin/csh

# --- Initialize Environment Modules ---
if ( -e /etc/profile.d/modules.csh ) then
    source /etc/profile.d/modules.csh
endif

set echo
set bomb = 0

# --- 1. LOAD JASMIN MODULES ---
module purge
module load jasmin-sci
module load jaspy

# --- 2. SET PATHS ---
set tarball_path     = "$HOME/test_MCM"
set runscript_path   = "$tarball_path/runscripts"
set model_code_path  = "$tarball_path/model_code"
set model_input_path = "$tarball_path/model_input_files"
set restart_path     = "$tarball_path/restart"

# Active working directory
set model_run        = "$tarball_path/run_dir"

mkdir -p $model_run
\rm -rf $model_run/*
cd $model_run

# --- 3. COMPILER & NETCDF FLAGS ---
set FC = "gfortran"
set FFLAGS = "-O0 -g -fbacktrace -cpp -ffixed-form -fdefault-real-8 -fdefault-double-8 -fallow-argument-mismatch -std=legacy -fdec -Wno-array-bounds"
set FFLAGS_READCTL = "-O0 -g -fbacktrace -cpp -ffixed-form -fallow-argument-mismatch -std=legacy -fdec"

# Auto-detect NetCDF include and library paths
set INC_DIR = ""

if ( `which nf-config` != "" ) then
    set INC_DIR = `nf-config --includedir`
    set LIB_NETCDF = "`nf-config --flibs` -Wl,-rpath,`nf-config --prefix`/lib"
endif

if ( "$INC_DIR" == "" || ! -e "$INC_DIR/netcdf.inc" ) then
    set INC_DIR = `find /apps/jasmin /opt/rh /usr -name "netcdf.inc" 2>/dev/null | grep -v "intel" | head -n 1 | xargs dirname`
    if ( "$INC_DIR" != "" ) then
        set LIB_DIR = `dirname $INC_DIR`/lib
        set LIB_NETCDF = "-L$LIB_DIR -lnetcdff -lnetcdf -Wl,-rpath,$LIB_DIR"
    endif
endif

if ( "$INC_DIR" == "" ) then
    echo "ERROR: Could not locate a valid netcdf.inc directory on JASMIN."
    exit 1
endif

set INC_NETCDF = "-I$INC_DIR"

if ( $?LD_LIBRARY_PATH ) then
    setenv LD_LIBRARY_PATH `${INC_DIR}/../lib`:${LD_LIBRARY_PATH}
endif

# --- 4. COMPILE ATMOSPHERE ---
cd $model_run
mkdir -p model/atm
cd model/atm
cp $model_code_path/atm_lib/*.[fFh] .
cp $model_code_path/ocn_lib/conblk.h .
/bin/rm -f ocean.F passup.F

# Convert Fortran includes to CPP includes
sed -i -E 's/^[ \t]*include[ \t]+["'\''"]([^"'\'']+)["'\''"]/#include "\1"/i' *.[fF] *.[hH]
sed -i 's/#include .netcdf.inc./#include "netcdf.inc"/g' *.[fF] *.[hH]

# Safeguard isecday division-by-zero
sed -i '/nday.*=.*ifcst.*\/.*isecday/i \      if (isecday .eq. 0) isecday = 86400' atmos.F

# Note: -Dix and -Diy flags are excluded here to prevent macro collision in parm.h
set aopt1 = '-Dr30 -Dk14 -Datmcpld -Dcpldleg3 -Dcldht93 -Dconsrv_ps -Dco2_360 -Dinternal_fft'
set aopt2 = '-Dwall_clock_time -Delmix4900 -Dhydrol -Dimpcit -Dmoist -Dnew_cld_absor -Dno_kflags_k1'
set aopt3 = '-Dno_neg_in_vertdf -Dno_reset_tmean -Dold_levels -Dpart_black_cirrus -Dprdcld -Drad'
set aopt4 = '-Dseanal -Dsponge -Dunitsk -Dvarhy -Dwet_ep_exp -Ddmptop20 -Dnew_rhxinv -Dtmean_warm'
set aopt  = "$aopt1 $aopt2 $aopt3 $aopt4"

echo ">>>>>== COMPILING ATMOSPHERE CODE ==<<<<<"
$FC $FFLAGS $INC_NETCDF $aopt -c *.[fF]
cp *.o $model_run/model/

# --- 5. COMPILE OCEAN ---
cd $model_run/model
mkdir -p ocn
cd ocn
cp $model_code_path/ocn_lib/*.[hfF] .

# Convert Fortran includes to CPP includes
sed -i -E 's/^[ \t]*include[ \t]+["'\''"]([^"'\'']+)["'\''"]/#include "\1"/i' *.[fF] *.[hH]
sed -i 's/#include .netcdf.inc./#include "netcdf.inc"/g' *.[fF] *.[hH]

# Note: -Dix and -Diy flags are excluded here to prevent macro collision in sealev.F
set opt1 = '-Dworldocn -Drigidlid -Dislands -Dhypergrid -Ddiskless -Df90type'
set opt2 = '-Dcyclic -Dfourfil -Dbumpkmu -Dkm18 -Docnr30'
set opt3 = '-Dconsthmix -Disopycmix -Dblhmix -Dconstvmix -Dblvmix -Dinland'
set opt4 = '-Dkeepterms -Dseaice'
set opt5 = '-Dselfdoc -Dsfctopog -Dreadrmsk -Dkdtravg -Dkdtermb -Dtestnorth -Dzonalavg'
set opt6 = '-Donetoone -Dgtime -Doldtime'
set opt7 = '-Dagetracers -Dseasonal -Dcpldleg3 -Damazon -Docncpld'
set opt  = "$opt1 $opt2 $opt3 $opt4 $opt5 $opt6 $opt7"

cp $model_run/model/atm/asblck.h .
cp $model_run/model/atm/ascoma.h .
cp $model_run/model/atm/ascomo.h .
cp $model_run/model/atm/cexpnam.h .

if ( -e denscoef.F ) /bin/rm -f denscoef.F

echo ">>>>>== COMPILING OCEAN CODE ==<<<<<"
$FC $FFLAGS $INC_NETCDF $opt -c *.[fF]

\rm -f ordleg.o
cp *.o $model_run/model/

# --- 6. LINK MODEL EXECUTABLE ---
cd $model_run/model
echo ">>>>>== LINKING MODEL EXECUTABLE ==<<<<<"
$FC $FFLAGS *.o $LIB_NETCDF -o $model_run/ctrs_06

# --- 7. STAGE RESTART & INPUT FILES ---
cd $model_run
set restart_path_lat = "$restart_path/initial"

cp $restart_path_lat/sstyce_r30.nc ./sstyce_r30_in.nc
cp $restart_path_lat/atmos_r30.nc ./atmos_r30_in.nc
cp $restart_path_lat/atm.intgls.r30 ./fort.71
cp $restart_path_lat/sealevel_r30.nc ./sealevel_r30_in.nc
cp $restart_path_lat/ocean_r30.nc ./ocean_r30_in.nc

cp $model_input_path/alb_kukla_r30.nc .
cp $model_input_path/ijrnf_r30.nc .
cp $model_input_path/zstarvar_r30.nc .
cp $model_input_path/regionmasks .
cp $model_input_path/northmasks .
cp $model_input_path/terrserr_r30.nc .

# --- 8. BUILD & RUN CONTROL READER ---
mkdir -p read_ctl
cd read_ctl
cp $model_code_path/read_ctl/*.[fFh] .

sed -i -E 's/^[ \t]*include[ \t]+["'\''"]([^"'\'']+)["'\''"]/#include "\1"/i' *.[fF] *.[hH]
sed -i 's/#include .netcdf.inc./#include "netcdf.inc"/g' *.[fF] *.[hH]

echo ">>>>>== COMPILING CONTROL READER ==<<<<<"
$FC $FFLAGS_READCTL $INC_NETCDF *.[fF] $LIB_NETCDF -o a.out
cp a.out $model_run/readr

cd $model_run
echo "  71" > fort.5
./readr < fort.5

set irt = `cat irt.data`

# --- 9. GENERATE NAMELISTS AND RUN INTEGRATION ---
set ndays = 31

# Atmosphere Namelist Setup
set alpha = 0.04
set dt = 216.0
set rk0 = 0.22e-6
set co2_equil = 360.0
set co2day_int = 5475

echo "ctrs_06   "                                         > fort.5
echo " &INDAT1 irt=$irt, NDAYS=$ndays /"                  >> fort.5
echo " &INDAT2 ALPHA=$alpha, DT=$dt, RK0=$rk0 /"          >> fort.5
echo " &INDAT3 intdk=10,ioprt=999999,intpr=80,intzm=80 /" >> fort.5
echo " &INHCO2 co2_equil=$co2_equil, co2day_int=$co2day_int /" >> fort.5

# Ocean Namelist Setup
cat > ocean.in << DELIMIT
 &contrl init=.false.,  restrt=.true., avterm=0.,
         nmix=17,      eb=.true.,  ncon=6,  pintro=.true.,
         days=$ndays, tsi=0.0416, dgnstc=5.0, travg=5.,
         histt=1.0,    snaps=99.9e9, prdiag=30.0,
         nsteps=48 /
 &eddy   am=1.2e9,    fkpm=30.0,  aidif=1.0,
         ah=0.4e7,    ahisop=1.0, slmxr=100.0,
         cdbot=0.001,
         afkph=0.65, dfkph=.74, sfkph=4.5e-5, zfkph=2500e2 /
 &tsteps dtts=1800., dtuv=1800., dtsf=1800. /
 &parms  mxscan=350, sor=1.575,  crit=.15e7,
         acor=0.0 /
 &iland  alonis=110.0, alatis=-85.0 /
DELIMIT

echo ">>>>>== EXECUTING MODEL ON JASMIN ==<<<<<"
./ctrs_06 < fort.5 > printout || set bomb = 1

if ($bomb == 0) then
   cp printout $runscript_path/printout.new
   echo "SUCCESS: Model run completed successfully."
else
   echo "ERROR: Model execution failed. Inspect $model_run/printout"
   exit 1
endif
