#!/bin/csh

if ( -e /etc/profile.d/modules.csh ) source /etc/profile.d/modules.csh
module purge
module load jasmin-sci
module load jaspy

set echo
set bomb = 0
set tarball_path    = "$PWD"
set runscript_path  = "$tarball_path/runscripts"
set model_code_path = "$tarball_path/model_code"
set model_input_path = "$tarball_path/model_input_files"
set restart_path    = "$tarball_path/restart"
set model_run       = "$tarball_path/_run_dir"

if ( -d "$model_run" ) \rm -rf "$model_run"
mkdir -p "$model_run"
cd "$model_run"

# --- Compiler & NetCDF setup for JASMIN ---
set FC = "gfortran"
set FFLAGS = "-O0 -g -fbacktrace -cpp -ffixed-form -fdefault-real-8 -fdefault-double-8 -fallow-argument-mismatch -std=legacy -fdec -Wno-array-bounds -fno-automatic -finit-local-zero"
set FFLAGS_READCTL = "-O0 -g -fbacktrace -cpp -ffixed-form -fallow-argument-mismatch -std=legacy -fdec"

set INC_DIR = ""
if ( `which nf-config` != "" ) then
    set INC_DIR = `nf-config --includedir`
    set LIB_NETCDF = "`nf-config --flibs` -Wl,-rpath,`nf-config --prefix`/lib"
endif
if ( "$INC_DIR" == "" || ! -e "$INC_DIR/netcdf.inc" ) then
    set INC_DIR = `find /apps/jasmin /opt/rh /usr -name "netcdf.inc" 2>/devnull | grep -v "intel" | head -n 1 | xargs dirname`
    if ( "$INC_DIR" != "" ) then
        set LIB_DIR = `dirname $INC_DIR`/lib
        set LIB_NETCDF = "-L$LIB_DIR -lnetcdff -lnetcdf -Wl,-rpath,$LIB_DIR"
    endif
endif
set INC_NETCDF = "-I$INC_DIR"

# --- COMPILING ATMOSPHERE CODE ---
mkdir -p model/atm
cd model/atm
cp $model_code_path/atm_lib/*.[fFh] .
cp $model_code_path/ocn_lib/conblk.h .
/bin/rm -f ocean.F passup.F

sed -i -E 's/^[ \t]*include[ \t]+["'\''"]([^"'\'']+)["'\''"]/#include "\1"/i' *.[fF] *.[hH]
sed -i 's/#include .netcdf.inc./#include "netcdf.inc"/g' *.[fF] *.[hH]
sed -i '/nday.*=.*ifcst.*\/.*isecday/i \      if (isecday .eq. 0) isecday = 86400' atmos.F

set aopt1 = '-Dr30 -Dk14 -Datmcpld -Dcpldleg3 -Dcldht93 -Dconsrv_ps -Dco2_360 -Dinternal_fft'
set aopt2 = ' -Dwall_clock_time -Delmix4900 -Dhydrol -Dimpcit -Dmoist -Dnew_cld_absor -Dno_kflags_k1'
set aopt3 = ' -Dno_neg_in_vertdf -Dno_reset_tmean -Dold_levels -Dpart_black_cirrus -Dprdcld -Drad'
set aopt4 = ' -Dseanal -Dsponge -Dunitsk -Dvarhy -Dwet_ep_exp -Ddmptop20 -Dnew_rhxinv -Dtmean_warm'
set aopt  = "$aopt1 $aopt2 $aopt3 $aopt4"

$FC $FFLAGS $INC_NETCDF $aopt -c *.[fF]
cp *.o ..
cd ..

# --- COMPILING OCEAN CODE ---
mkdir ocn
cd ocn
cp  $model_code_path/ocn_lib/*.[hfF] .

sed -i -E 's/^[ \t]*include[ \t]+["'\''"]([^"'\'']+)["'\''"]/#include "\1"/i' *.[fF] *.[hH]
sed -i 's/#include .netcdf.inc./#include "netcdf.inc"/g' *.[fF] *.[hH]

set opt1 = '-Dworldocn -Drigidlid -Dislands -Dhypergrid -Ddiskless -Df90type'
set opt2 = '-Dcyclic -Dfourfil -Dbumpkmu -Dkm18 -Docnr30 '
set opt3 = '-Dconsthmix -Disopycmix -Dblhmix -Dconstvmix -Dblvmix -Dinland'
set opt4 = '-Dkeepterms -Dseaice'
set opt5 = '-Dselfdoc -Dsfctopog -Dreadrmsk -Dkdtravg -Dkdtermb -Dtestnorth -Dzonalavg'
set opt6 = '-Donetoone -Dgtime -Doldtime'
set opt7 = '-Dagetracers -Dseasonal -Dcpldleg3 -Damazon -Docncpld'

echo " opt1 = $opt1 "
echo " opt2 = $opt2 "
echo " opt3 = $opt3 "
echo " opt4 = $opt4 "
echo " opt5 = $opt5 "
echo " opt6 = $opt6 "
echo " opt7 = $opt7 "

cp ../../model/atm/asblck.h .
cp ../../model/atm/ascoma.h .
cp ../../model/atm/ascomo.h .
cp ../../model/atm/cexpnam.h .

if ( -e denscoef.F ) /bin/rm -f denscoef.F

echo ">>>>>== COMPILING OCEAN CODE ==<<<<< "
$FC $FFLAGS $INC_NETCDF $opt1 $opt2 $opt3 $opt4 $opt5 $opt6 $opt7 -c *.[fF]

\rm -f ordleg.o
cp *.o ..
cd ..

# --- LINKING MODEL EXECUTABLE ---
$FC $FFLAGS *.o $LIB_NETCDF -o ctrs_06

set nyear = 1
set endyear = 1
set endmonth = 1
set lastmonth = 12
set restart_path_lat = "$restart_path/initial"
set prinito = "true"

while ($nyear <= $endyear)
   set imonth = 1
   while ($imonth <= $endmonth)

      # Copy initial restart files only for the first month
      if ($nyear == 1 && $imonth == 1) then
         cp $restart_path_lat/sstyce_r30.nc sstyce_r30_in.nc
         cp $restart_path_lat/atmos_r30.nc atmos_r30_in.nc
         cp $restart_path_lat/atm.intgls.r30 fort.71
         cp $restart_path_lat/atm.intgls.r30 fort.77
         cp $restart_path_lat/sealevel_r30.nc sealevel_r30_in.nc
         cp $restart_path_lat/ocean_r30.nc ocean_r30_in.nc
      endif

      cp $model_input_path/alb_kukla_r30.nc .
      cp $model_input_path/ijrnf_r30.nc .
      cp $model_input_path/zstarvar_r30.nc .
      cp $model_input_path/regionmasks .
      cp $model_input_path/northmasks .
      cp $model_input_path/terrserr_r30.nc .

      mkdir -p read_ctl
      cd read_ctl
      cp $model_code_path/read_ctl/*.[fFh] .
      sed -i -E 's/^[ \t]*include[ \t]+["'\''"]([^"'\'']+)["'\''"]/#include "\1"/i' *.[fF] *.[hH]
      sed -i 's/#include .netcdf.inc./#include "netcdf.inc"/g' *.[fF] *.[hH]

      $FC $FFLAGS_READCTL $INC_NETCDF *.[fF] $LIB_NETCDF -o a.out
      cp a.out ../readr
      cd ..

      echo "  71" > fort.5

      ./readr < fort.5
      set irt = `cat irt.data`
      setenv model_month `cat month.data`
      set iyear = `cat iyear.data`

      @ yyear = $iyear
      setenv model_year $yyear

      set count = 1

      set month_list = (jan feb mar apr may jun jul aug sep oct nov dec)
      set days_list = (31 28 31 30 31 30 31 31 30 31 30 31)

      set model_month = $month_list[$imonth]
      set ndays = $days_list[$imonth]

      set nnyear = $iyear
      setenv model_year $nnyear

      while ($month_list[$count] != $model_month && $count < 12)
         @ count = $count + 1
      end

      if ($count > 12) then
         echo "We have problems. count > 12, count= $count"
         exit
      endif
      set ndays = $days_list[$count]

      set alpha = 0.04
      set dt = 216.0
      set rk0 = 0.22e-6

      set co2_equil = 360.0
      set co2day_int = 5475

      echo "ctrs_06   "                                     > fort.5
      echo " &INDAT1 irt=$irt, NDAYS=$ndays         &END"  >> fort.5
      echo " &INDAT2 ALPHA=$alpha, DT=$dt, RK0=$rk0 &END"  >> fort.5
      echo " &INDAT3 intdk=10,ioprt=999999,intpr=80,intzm=80 &END"  >> fort.5
      echo " &INHCO2 co2_equil=$co2_equil, co2day_int=$co2day_int  &END" >> fort.5
      echo "" >> fort.5

      cat fort.5

      set nyrdiag = 1
      set nyrtavg = 1
      set nyears = 1
      set nyrdiag = `expr $nyrdiag \* 365 `
      set nyrtavg = `expr $nyrtavg \* 365 `
      set ndayso = $ndays
      set ninit = ".false."

      # Dynamic calculation: 48 ocean timesteps per day
      @ ocn_steps = $ndayso * 48

      cat > ocean.in << DELIMIT
 &contrl init=$ninit,  restrt=.true., avterm=0.,
         nmix=17,      eb=.true.,  ncon=6,  pintro=$prinito,
         days=$ndayso, tsi=0.0416, dgnstc=5.0, travg=5.,
         histt=1.0,    snaps=99.9e9, prdiag=30.0,
         nsteps=$ocn_steps                       &end
 &eddy   am=1.2e9,    fkpm=30.0,  aidif=1.0,
         ah=0.4e7,    ahisop=1.0, slmxr=100.0,
         cdbot=0.001,
         afkph=0.65, dfkph=.74, sfkph=4.5e-5, zfkph=2500e2 &end
 &tsteps dtts=1800., dtuv=1800., dtsf=1800.,    &end
 &parms  mxscan=350, sor=1.575,  crit=.15e7,
         acor=0.0                               &end
 &iland  alonis=110.0, alatis=-85.0,            &end
DELIMIT

      echo ">>>>>== CONTENTS OF ocean.in ==<<<<< "
      cat ocean.in

      sync
      ./ctrs_06 < fort.5 > printout || set bomb = 1

      if ($bomb != 0) then
         echo "ERROR: Model execution failed at year $nyear month $imonth."
         exit 1
      endif

      cp printout $runscript_path/printout.new

      @ imonth = $imonth + 1
      set first_run = 0
      set init = 0
      set ninit = ".false."
      set prinito = ".false."

   end
   @ nyear = $nyear + 1
end
